#!/usr/bin/env bash
#script for load balance
sudo apt-get -y update
sudo apt-get -y install nginx
temp="/etc/nginx/sites-avaiable/default"
sudo sed -i "37i \\\t add_header X-Served-By $HOSTNAME;\n" $temp
sudo service nginx restart
