#!/usr/bin/env bash
#script for load balance
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
temp = /etc/nginx/nginx.conf
sudo sed -i "16i \\\tadd_header X-Served-By $HOSTNAME;\n" $temp
sudo service nginx restart
