#!/usr/bin/env bash                                                                                                                                          
#conf load balancer                                                                                                                                          
sudo apt install -y haproxy=1.5\*
temp="/etc/haproxy/haproxy.cfg"
echo -e "frontend piglet                                                                                                                                     
\tbind *:80                                                                                                                                                  
\tmode http                                                                                                                                                  
\tdefault_backend http_behind                                                                                                                                
backend http_behind                                                                                                                                          
\tmode http                                                                                                                                                  
\tbalance roundrobin                                                                                                                                         
\toption forwardfor                                                                                                                                          
\tserver 262-web-01 35.229.52.77:80 check                                                                                                                    
\tserver 262-web-02 35.237.249.255:80 check" |  sudo tee -a $temp
sudo service haproxy restart
