#!/usr/bin/env bash
#conf load balancer
sudo apt install -y haproxy=1.5\*
temp="/etc/haproxy/haproxy.config"
echo -e "frontend piglet
\tbind *:80
\tmode http
\tdefault_backend poohbear
backend poohbear
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver 262-web-01 35.229.52.77:80 check
\tserver 262-web-02 35.237.249.255:80 check" | sudo tee -a $temp
sudo service haproxy restart