#!/usr/bin/env bash
#script to display numbers 1-20 display messages on different iterations

i=1
while [ $i -le 20 ]
do
    echo "$i"
    case "$i" in
	4) echo "bad luck from China"
	    ;;
	9) echo "bad luck from Japan"
	    ;;
	17) echo "bad luck from Italy"
	    ;;
    esac 
    let i++
done
