#!/usr/bin/env bash
#script to display time 


hour=0
minutes=1

while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
  	let hour++
	minutes=1
      	while [ "$minutes" -le 59 ]
      	do
	    echo "$minutes"
	    let minutes++
	done
done
